"""initial schema with 5 tables, pgvector, hybrid search

Revision ID: cdb17f5bb3f6
Revises: 
Create Date: 2026-05-26 12:38:29.411073

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb17f5bb3f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Activate pgvector extension (must be before any VECTOR column)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_thread_id'), 'audit_log', ['thread_id'], unique=False)
    op.create_table('kb_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slack_user_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_slack_user_id'), 'users', ['slack_user_id'], unique=True)
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('assigned_engineer_id', sa.UUID(), nullable=True),
    sa.Column('resolver_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_escalations_assigned_engineer', 'escalations', ['assigned_engineer_id'], unique=False, postgresql_where="status = 'waiting_for_human'")
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_escalations_thread_id'), 'escalations', ['thread_id'], unique=False)
    op.create_index('uq_escalations_open_per_thread', 'escalations', ['thread_id'], unique=True, postgresql_where="status = 'waiting_for_human'")
    op.create_table('kb_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['kb_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_kb_chunks_doc_idx')
    )
    op.create_index('idx_kb_chunks_content_tsv', 'kb_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_kb_chunks_document_id'), 'kb_chunks', ['document_id'], unique=False)
    op.execute(
        "CREATE INDEX idx_kb_chunks_embedding "
        "ON kb_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    # ============================================================
    # updated_at trigger — applied to all tables with updated_at column
    # ============================================================
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # Apply trigger to each table with updated_at
    for table in ['users', 'escalations', 'kb_documents', 'kb_chunks']:
        op.execute(f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
        # Drop triggers first
    for table in ['users', 'escalations', 'kb_documents', 'kb_chunks']:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    # Drop HNSW index
    op.execute("DROP INDEX IF EXISTS idx_kb_chunks_embedding")
    # ... existing autogenerated code (drop tables) ...
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_chunks_document_id'), table_name='kb_chunks')
    op.drop_index('idx_kb_chunks_content_tsv', table_name='kb_chunks', postgresql_using='gin')
    op.drop_table('kb_chunks')
    op.drop_index('uq_escalations_open_per_thread', table_name='escalations', postgresql_where="status = 'waiting_for_human'")
    op.drop_index(op.f('ix_escalations_thread_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index('idx_escalations_assigned_engineer', table_name='escalations', postgresql_where="status = 'waiting_for_human'")
    op.drop_table('escalations')
    op.drop_index(op.f('ix_users_slack_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('kb_documents')
    op.drop_index(op.f('ix_audit_log_thread_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # Note: we don't drop the vector extension — it may be used elsewhere
    # ### end Alembic commands ###
